//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FileMap.rsrc.rc
//
#define IDD_MAIN                        101
#define IDC_LOAD_FILE                   101
#define IDC_SAVE_DISASM                 102
#define IDC_PE_EDITOR                   103
#define ID_PROCESS_SHOW                 104
#define ID_TOOLBAR                      105
#define ID_EP_SHOW                      106
#define ID_CODE_SHOW                    107
#define ID_ADDR_SHOW                    108
#define ID_SHOW_IMPORTS                 109
#define ID_SHOW_XREF                    110
#define ID_EXEC_JUMP                    111
#define ID_RET_JUMP                     112
#define ID_EXEC_CALL                    113
#define ID_RET_CALL                     114
#define ID_XREF                         115
#define ID_DOCK_DBG                     116
#define ID_HEX                          117
#define ID_SEARCH                       118
#define ID_PATCH                        119
#define ID_SCRIPT                       120
#define IDR_MENU1                       134
#define IDR_MAIN                        134
#define IDD_EDITOR                      135
#define IDD_SECTION_EDITOR              136
#define IDR_ACCELERATOR1                145
#define IDR_SECTION                     148
#define IDD_EDIT_SEC_HEADER             149
#define IDI_EXE                         153
#define IDD_SECTIONS_TABLE              154
#define IDB_PE_TREE                     157
#define IDD_PE_DIRECTORY                158
#define IDI_INFO_BEWARE                 160
#define IDI_INFO_HELP                   161
#define IDD_PROCESS                     162
#define IDR_PROCESSES                   163
#define IDB_EDIT_PE                     164
#define IDB_DUMP_PE                     165
#define IDB_TABLE_PE                    166
#define IDB_TOOLBARHOT                  174
#define IDB_TOOLBAR                     175
#define IDB_PROCESS_KILL                176
#define IDB_PROCESS_DUMP                177
#define IDB_PROCESS_REFRESH             178
#define IDB_PROCESS_PRIORITY            179
#define IDD_PARTIAL_DUMP                180
#define IDB_PARTIAL_DUMP                181
#define IDB_IMPORTS_TREE                182
#define IDD_PE_IMPORTS                  183
#define IDB_EXPORTS_TREE                184
#define IDD_DISASM                      185
#define IDD_GOTO_ADDRESS                186
#define IDD_COMMENTS                    187
#define IDD_IMPORTS                     188
#define IDD_ADVANCED_OPTIONS            189
#define IDD_ABOUT                       190
#define IDD_STRING_REF                  191
#define IDD_DISASM_COLORS               192
#define IDR_BINARY                      196
#define IDR_REGION                      198
#define IDR_XREF                        200
#define IDR_XREF_PIC                    201
#define IDD_XREF                        202
#define IDD_HEXEDITOR                   203
#define IDR_HEX                         204
#define IDD_FIND                        207
#define IDD_PATCHER                     208
#define IDD_DATA_SEGMENTS               209
#define IDR_DISASM                      210
#define IDB_RC_XREF                     212
#define IDB_RC_IMP                      213
#define IDB_RC_REF                      214
#define IDB_RC_SAVE                     215
#define IDB_RC_APPEARANCE               216
#define IDB_RC_FIND                     217
#define IDB_RC_HEXEDIT                  218
#define IDB_RC_PATCHER                  219
#define IDB_RC_EP                       220
#define IDB_RC_ADDR                     221
#define IDB_RC_CODE                     222
#define IDB_RC_COPY                     223
#define IDB_RC_COPY_FILE                224
#define IDB_RC_SELECT_ALL               225
#define IDB_FUNCTION_STRINGS            226
#define IDB_BITMAP1                     227
#define IDD_FUNCTIONS_ENTRYPOINTS       228
#define IDB_RC_DATA_MANAGER             229
#define IDB_RC_FUNC_MANAGER             230
#define IDB_RC_DEFINE_DATA              231
#define IDB_RC_DEFINE_FUNC              232
#define IDD_WIZARD                      233
#define IDD_WIZARD_DATA                 234
#define IDD_WIZARD_CODE                 235
#define IDD_WIZARD_HEADER               236
#define IDD_WIZARD_PREVIEW              237
#define IDD_TOOLTIP                     240
#define IDD_SCRIPT_EDITOR               241
#define IDR_MANIFEST                    243
#define IDC_LIST                        1060
#define IDC_NUMOFSECTIONS               1061
#define IDC_SAVEPE                      1062
#define IDC_SIZEOFIMAGE                 1063
#define IDC_SIZEOFCODE                  1064
#define IDC_BASEOFCODE                  1065
#define IDC_TIMEANDDATE                 1066
#define IDC_IMAGEBASE                   1067
#define IDC_ENTRYPOINT                  1068
#define IDC_BASEOFDATA                  1069
#define IDC_SECTIONS_VIEW               1071
#define IDC_DISASM                      1072
#define IDC_MAGIC                       1078
#define IDC_FILEALLIGMENT               1079
#define IDC_MESSAGE1                    1079
#define IDC_SUBSYSTEM                   1080
#define IDC_SIZEOFHEADERS               1081
#define IDC_MESSAGE2                    1081
#define IDC_CHARACTERISTICS             1082
#define IDC_CHECKSUM                    1083
#define IDC_NUMBEROFRVA                 1084
#define IDC_SECALIGN                    1085
#define IDC_SECTIONS                    1086
#define IDC_EDIT_SEC_NAME               1087
#define IDC_EDIT_SEC_RVA                1088
#define IDC_EDIT_SEC_VSIZE              1089
#define IDC_EDIT_SEC_RAW                1090
#define IDC_EDIT_SEC_RSIZE              1091
#define IDC_EDIT_SEC_CHAR               1092
#define IDC_EDIT_SEC_SAVE               1093
#define IDC_EDIT_SEC_EXIT               1098
#define IDC_SECTIONS_TREE               1099
#define IDC_EXPORT_RVA                  1100
#define IDC_EXPORT_SIZE                 1101
#define IDC_IMPORT_RVA                  1102
#define IDC_SEC_DIRECTORY               1102
#define IDC_IMPORT_SIZE                 1103
#define IDC_RESOURCE_RVA                1104
#define IDC_RESOURCE_SIZE               1105
#define IDC_EXCEPTION_RVA               1106
#define IDC_EXCEPTION_SIZE              1107
#define IDC_SECUTIRY_RVA                1108
#define IDC_SECUTIRY_SIZE               1109
#define IDC_BASERELOC_RVA               1110
#define IDC_BASERELOC_SIZE              1111
#define IDC_DEBUG_RVA                   1112
#define IDC_DEBUG_SIZE                  1113
#define IDC_COPYRIGHT_RVA               1114
#define IDC_COPYRIGHT_SIZE              1115
#define IDC_GLOBALPTR_RVA               1116
#define IDC_GLOBALPTR_SIZE              1117
#define IDC_TLS_RVA                     1118
#define IDC_TLS_SIZE                    1119
#define IDC_LOADCONFIG_RVA              1120
#define IDC_LOADCONFIG_SIZE             1121
#define IDC_BOUNDIMPORT_RVA             1122
#define IDC_BOUNDIMPORT_SIZE            1123
#define IDC_IAT_RVA                     1124
#define IDC_IAT_SIZE                    1125
#define IDC_DIRECTORY_SAVE              1126
#define IDC_DIRECTORY_CANCEL            1127
#define IDC_PE_SECTION_CANCEL           1128
#define IDC_LISTPROC                    1129
#define IDC_SEC_TABLE_EXIT              1132
#define IDC_MODULES                     1133
#define ID_PARTIAL_DUMP_SAVE            1135
#define ID_PARTIAL_DUMP_EXIT            1136
#define IDC_BASE_ADDRESS                1137
#define IDC_DUMP_SIZE                   1138
#define IDC_REBUILD_PE                  1139
#define IDC_IMPORTS_TREE                1140
#define IDC_PE_IMPORTS                  1141
#define IDC_SHOW_IMPORTS                1143
#define IDC_SHOW_EXPORTS                1144
#define IDC_EXPORTS_TREE                1145
#define IDC_FILE_FORMAT                 1146
#define IDC_CPUS                        1147
#define IDC_DISASM_FILE                 1148
#define IDC_CANCEL                      1149
#define IDC_LOADED_FILE                 1150
#define IDC_SET_CPU                     1151
#define IDC_UPPERCASE_DISASM            1153
#define IDC_SHOW_SECTIONS               1154
#define IDC_SHOW_ADDR                   1155
#define IDC_SHOW_REMARKS                1156
#define IDC_SHOW_OPCODES                1157
#define IDC_SHOW_ASSEMBLY               1158
#define IDC_FORCE_DISASM                1161
#define IDC_GOTO                        1162
#define IDC_ADDRESS                     1164
#define IDC_INC_BYTES                   1165
#define IDC_BYTE_EP                     1166
#define IDC_DISASM_PROGRESS             1167
#define IDC_MESSAGE3                    1168
#define IDC_FORCE_EP                    1169
#define IDC_SET                         1171
#define IDC_COMMENT                     1172
#define IDC_IMPORT_CANCEL               1173
#define IDC_FIND_IMPORT                 1175
#define IDC_TOOLBAR_SEP                 1177
#define IDC_TOOLBAR_SEP2                1178
#define IDC_IMPORT_LIST                 1178
#define IDC_ADD_SEMI                    1179
#define IDC_ADVANCE_CANCEL              1180
#define IDC_SAVE_OPTIONS                1184
#define IDC_ADVANCED                    1186
#define IDC_ABOUT_CANCEL                1187
#define IDC_SHOW_DBG_IMP                1189
#define IDC_FIND_REF                    1190
#define IDC_REF_LIST                    1191
#define IDC_REF_CANCEL                  1192
#define IDC_ADDR_COLOR                  1193
#define IDC_ADDR_BG_COLOR               1194
#define IDC_OP_COLOR                    1195
#define IDC_OP_BG_COLOR                 1196
#define IDC_ASM_COLOR                   1197
#define IDC_ASM_BG_COLOR                1198
#define IDC_REM_COLOR                   1199
#define IDC_REM_BG_COLOR                1200
#define IDC_SAVE                        1201
#define IDC_CALL_COLOR                  1202
#define IDC_API_COLOR                   1203
#define IDC_JUMP_COLOR                  1204
#define IDC_DISASM_BG_COLOR             1205
#define IDC_COLOR_SCHEME                1206
#define IDC_AUTO_DB                     1207
#define IDC_FAKE_EDIT                   1209
#define IDC_EXIT_ABOUT                  1210
#define IDC_IMPORTS_LIST                1211
#define IDC_EXACT_STRING                1212
#define IDC_CONTAIN                     1213
#define IDC_STRING_REF_LV               1214
#define IDC_EXACT_REF_STRING            1215
#define IDC_REF_CONTAIN                 1216
#define IDC_XREF_OK                     1217
#define IDC_XREF_LIST                   1219
#define IDC_RAHEXEDIT                   1221
#define IDC_FIND_STRING                 1222
#define IDC_FIND_IT                     1223
#define IDC_MATCH_CASE                  1224
#define IDC_WHOLE_WORD                  1225
#define IDC_FIND_NEXT                   1226
#define IDC_HEX                         1227
#define IDC_PATCH                       1228
#define IDC_BACKUP                      1229
#define IDC_PREVIEW                     1230
#define IDC_PATCHER_EXIT                1232
#define IDC_DATA_CREATE_SEGMENTS        1233
#define IDC_START_ADDR                  1234
#define IDC_END_ADDR                    1235
#define IDC_ADD_NEW                     1236
#define IDC_DATA_LIST                   1237
#define IDC_DELETE_DATA                 1239
#define IDC_EXIT_DATA                   1240
#define IDC_FIRST_PASS                  1241
#define IDC_START_FADDR                 1242
#define IDC_END_FADDR                   1243
#define IDC_ADD_NEW_F                   1244
#define IDC_DELETE_FDATA                1245
#define IDC_FDATA_LIST                  1246
#define IDC_EXIT_FDATA                  1247
#define IDC_FDATA_CREATE_EP             1248
#define IDC_SIGNATURES                  1249
#define IDC_WIZARD_PATH_NEXT            1250
#define IDC_MASM_PRJ_PATH_EDIT          1251
#define IDC_PRJ_PATH_SELECT             1252
#define IDC_MASM_PATH_EDIT              1253
#define IDC_MASM_PATH_SELECT            1254
#define IDC_WIZARD_PATH_CANCEL          1255
#define IDC_WIZARD_DATA_BACK            1256
#define IDC_WIZARD_DATA_NEXT            1257
#define IDC_RENAME_EDIT                 1260
#define IDC_DATA_RENAME                 1261
#define IDC_FUNCTIONS_LIST              1262
#define IDC_SUB_LIST                    1263
#define IDC_WIZARD_CODE_BACK            1264
#define IDC_WIZARD_CODE_NEXT            1265
#define IDC_PROTO_EDIT                  1267
#define IDC_PARAM_TYPE                  1268
#define IDC_CREATE_PROTO                1269
#define IDC_ADD_TYPE                    1270
#define IDC_PARAM_OTHER                 1271
#define IDC_PROC_EDIT                   1272
#define IDC_WIZARD_HEADER_BACK          1273
#define IDC_WIZARD_HEADER_NEXT          1274
#define IDC_MACHINE                     1275
#define IDC_CASEMAP                     1278
#define IDC_EP_NAME                     1279
#define IDC_MODEL_SYSCALL               1282
#define IDC_MODEL_STDCALL               1283
#define IDC_MODEL_C                     1284
#define IDC_MODEL_FORTRAN               1285
#define IDC_MODEL_PASCAL                1286
#define IDC_MODEL_BASIC                 1287
#define IDC_MODEL_TINY                  1288
#define IDC_MODEL_MEDIUM                1289
#define IDC_MODEL_SMALL                 1290
#define IDC_MODEL_LARGE                 1291
#define IDC_MODEL_COMPACT               1292
#define IDC_MODEL_HUGE                  1293
#define IDC_MODEL_FLAT                  1294
#define IDC_SET_OPTIONS                 1296
#define IDC_WIZARD_MMX                  1297
#define IDC_WIZARD_NOLIST               1298
#define IDC_WIZARD_NOLISTMACRO          1299
#define IDC_WIZARD_NOLISTIF             1300
#define IDC_WIZARD_LIST                 1301
#define IDC_WIZARD_LALL                 1302
#define IDC_WIZARD_LIBS                 1303
#define IDC_WIZARD_INCLUDE              1304
#define IDC_WIZARD_BUILD                1304
#define IDC_WIZARD_PREV_BACK            1305
#define IDC_WIZARD_PREVIEW              1306
#define IDC_PREV_COMMENTS               1307
#define IDC_WIZARD_PREV_CLOSE           1308
#define IDC_DATA_DELETE                 1309
#define IDC_CREATE_EMPTY                1310
#define IDC_CREATE_EXPORT               1311
#define IDC_CREATE_IMPORT               1312
#define IDC_CREATE_AUTO                 1313
#define IDC_GOTO_ENTRY_F                1314
#define IDC_LOAD_MAP                    1315
#define IDC_TOOLTIP_LIST                1317
#define IDC_FUNCTION_NAME               1320
#define IDC_UPDATE_FDATA                1321
#define IDC_AUTO_SEARCH_CREATE          1323
#define IDC_SCRIPT_EDIT                 1324
#define IDC_SCRIPT_MESSAGE              1325
#define IDC_PROCESS_SEARCH              1326
#define IDC_LOADFILE                    40001
#define IDC_EXIT                        40002
#define IDC_MENUABOUT                   40004
#define ID_PE_EDIT                      40006
#define IDC_CLEARDEBUG                  40014
#define COLOR_D_TEXT                    40016
#define TEXT_D_BG                       40017
#define BG_D_COLOR                      40018
#define ID_EDIT_SECTION                 40022
#define ID_SAVE_SECTION                 40023
#define ID_SEC_TABLE                    40024
#define ID_PROCESSES                    40025
#define ID_KILL_PROCESS                 40026
#define ID_PROCESSES_REFRESHVIEW        40027
#define ID_DUMP_PROCESS                 40028
#define ID_PROCESS_REAL                 40029
#define ID_PROCESS_HIGH                 40030
#define ID_PROCESS_NORMAL               40031
#define ID_PROCESS_IDLE                 40032
#define ID_PARTIAL_DUMP                 40033
#define IDC_DISASM_FONT                 40034
#define IDC_DEBUG_FONT                  40035
#define IDC_GOTO_START                  40036
#define IDC_GOTO_ENTRYPOINT             40037
#define IDC_GOTO_ADDRESS                40038
#define ID_GOTO_JUMP                    40039
#define ID_GOTO_RETURN_JUMP             40040
#define ID_GOTO_EXECUTECALL             40041
#define ID_GOTO_RETURN_CALL             40042
#define IDC_START_DISASM                40043
#define IDC_STOP_DISASM                 40044
#define IDC_PAUSE_DISASM                40045
#define IDC_DISASM_IMP                  40046
#define IDC_STR_REFERENCES              40047
#define IDC_DISASM_APPEARANCE           40048
#define IDC_XREF_MENU                   40049
#define IDC_DOCK_DEBUG                  40050
#define IDM_OPEN_FILE                   40051
#define IDM_SAVE_FILE                   40052
#define IDM_SAVE_FILE_AS                40053
#define IDM_EXIT                        40054
#define IDM_ADDRESS                     40055
#define IDM_ASCII                       40056
#define IDM_UPPERCASE                   40057
#define IDC_HEX_EDITOR                  40058
#define IDM_COPY                        40059
#define IDM_CUT                         40060
#define IDM_PASTE                       40061
#define IDM_REDO                        40062
#define IDM_UNDO                        40063
#define IDM_DELETE                      40064
#define IDM_FIND                        40065
#define IDM_PATCHER                     40066
#define IDM_OPEN_PROJECT                40067
#define IDM_SAVE_PROJECT                40068
#define IDM_GOTO_EP                     40069
#define IDM_GOTO_ADDR                   40070
#define IDM_GOTO_CODE                   40071
#define IDM_IMPORTS                     40072
#define IDM_STR_REF                     40073
#define IDM_XREF                        40074
#define IDM_CODEPATCH                   40075
#define IDM_HEX_EDIT                    40076
#define IDM_PE_EDIT                     40077
#define IDM_PROCESS_MANAGER             40078
#define IDM_FIND_IN_DISASM              40079
#define IDM_DISASM_APPEARANCE           40080
#define IDM_COPY_DISASM                 40082
#define IDM_COPY_FILE                   40083
#define IDM_SELECT_ALL                  40084
#define IDM_COPY_DISASM_FILE            40086
#define IDM_COPY_DISASM_CLIP            40087
#define IDM_SELECT_ALL_ITEMS            40089
#define IDC_PRODUCE_MASM                40090
#define IDC_DEFINE_DATA_SEGS            40092
#define IDC_DEFINE_FUNCTION_EP          40093
#define IDC_DEFINE_SELECTED_DATA        40096
#define IDC_DEFINE_SELECTED_EP          40097
#define IDC_PRODUCE_VIEW                40098
#define IDC_CLOSEFILE                   40099
#define IDC_DISASM_ADD_COMMENT          40101
#define IDC_EXPORT_MAP_PVDASM           40104
#define IDC_PVSCRIPT_ENGINE             40105
#define IDC_PVSCRIPT                    40106
#define IDC_DARK_MODE                   40107
#define IDC_SPLITTER                    40108
#define IDC_SHOW_COMMENTS               40109
#define IDD_COMMENT_REF                 242
#define IDC_COMMENT_REF_LV              1326
#define IDC_COMMENT_FIND                1327
#define IDC_COMMENT_CANCEL              1328
#define IDC_COMMENT_EXACT               1329
#define IDC_COMMENT_CONTAIN             1330
#define IDC_COMMENT_FINDNEXT            1331
#define IDC_IMPORT_FINDNEXT             1332
#define IDC_STRREF_FINDNEXT             1333

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         40110
#define _APS_NEXT_CONTROL_VALUE         1334
#define _APS_NEXT_SYMED_VALUE           121
#endif
#endif
